1.21.1-NEOFORGE:
  - '(1.21.1 - NEOFORGE|- \[X\] 1.21.1 \| NEOFORGE)'

1.21.1-FABRIC:
  - '(1.21.1 - FABRIC|- \[X\] 1.21.1 \| FABRIC)'

1.20.1-FORGE:
  - '(1.20.1 - FORGE|- \[X\] 1.20.1 \| FORGE)'

1.20.1-FABRIC:
  - '(1.20.1 - FABRIC|- \[X\] 1.20.1 \| FABRIC)'

server:
  - '(server|Server)'