name: Undetected StoneType
description: Did StoneZone fails to detect StoneType? Report it.
title: "[🗃]: "
labels: ["enhancement", "undetection"]
body:
  - type: markdown
    attributes:
      value: |
        DETAILS

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: "Code of Conduct"
      options:
        - label: "Always check you are using the latest version of the mods and its dependencies"
          required: true
        - label: "The undetected StoneType must have 3 unique wordings as a name. Example: enlightened_end:void_shale_bricks"
          required: true
        - label: "Check the undetected StoneType for the sound, if it's not BASE_DRUM, then it's an issue on the StoneType's mod. Report it to the DEV"
          required: true
        - label: "Check whether there are a similar issue listed or not."
          required: true
        - label: "I HAVE READ ABOVE & CONFIRMED THEM."
          required: true

  - type: dropdown
    id: version-loader
    attributes:
      label: "Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)"
      description: "What's the Minecraft version & loader"
      options:
        - DO NOT FORGET the selected one is correct
        - 1.21.1 - FABRIC
        - 1.20.1 - FABRIC
        - 1.21.1 - NEOFORGE
        - 1.20.1 - FORGE
      default: 0
    validations:
      required: true

  - type: input
    id: nameStoneMod
    attributes:
      label: Name of Stone Mod
      description: Name of Stone Mod & modID
      placeholder: ex. Alex's Cave (alexscaves)
    validations:
      required: true

  - type: textarea
    id: list_of_stones
    attributes:
      label: "List of Undetected StoneTypes"
      description: "StoneZone failed to detect StoneTypes that should be included. The example below is an excellent to follow"
      placeholder: "- [ ] modID:nameStoneType (modID:nameStoneType_bricks)\n- [ ]  alexscaves:galena (alexscaves:galena_bricks)\n- [ ]  alexscaves:radrock (alexscaves:radrock_bricks)\n- [ ]  alexscaves:abyssmarine (alexscaves:abyssmarine_bricks)\n- [ ]  alexscaves:guanostone (alexscaves:guanostone_bricks)"
    validations:
      required: true

  - type: textarea
    id: other_details
    attributes:
      label: "Other Details"
      description: "Other Detail I should be aware of?"
      placeholder: "Bountiful Fares is a special case since it has a feldspar item (bountifulfares:feldspar) that isn't the stone block, but is used to make the stone block."
    validations:
      required: false
